services:
  avtobaraka-api:
    container_name: avto-baraka-api
    restart: always
    image: node:20.10.0
    ports:
      - 4001:3004
    volumes:
      - ./:/usr/src/avtobaraka
    working_dir: /usr/src/avtobaraka
    networks:
      - monorepo-network
    command: bash -c "npm install && npm run build && npm run start:prod"

  avtobaraka-batch:
    container_name: avto-baraka-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4005:3005
    volumes:
      - ./:/usr/src/avtobarka
    working_dir: /usr/src/avtobarka
    networks:
      - monorepo-network
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
# avtobaraka-api: localhost:4000 <=> 3000
# avtobaraka-api: localhost:4004 <=> 3004
# avtobaraka-batch: localhost:4005 <=> 3005
# docker compose up -d
# docker compose stop
# docker compose start
# docker compose restart
